CALL FT_DROP_INDEX('PUBLIC', 'MOLENS');
CALL FT_CREATE_INDEX('PUBLIC', 'MOLENS', 'NAAM,BOUWJAAR,TYPE,KENMERKEN,FUNCTIE,ADRES,MOLENAAR,EIGENAAR,PLAATS');

SELECT M.* FROM FT_SEARCH_DATA('arend vincent', 0, 0) FT, MOLENS M
WHERE FT."TABLE"='MOLENS' AND M.MOLENID=FT.KEYS[1];

SELECT FT.keys[1] FROM FT_SEARCH_DATA('Arend', 0, 0) FT
WHERE FT."TABLE"='MOLENS'
